# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: dnstrace
builds:
  - binary: dnstrace
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=hatamiarash7
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - amd64
      - arm64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: md5
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
brews:
  - name: dnstrace
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: Arash Hatami
      email: info@arash-hatami.ir
    homepage: "https://github.com/hatamiarash7/dnstrace"
    description: " DNS resolution tracing tool."
    license: "MIT"
    repository:
      owner: hatamiarash7
      name: homebrew-tap
      branch: main
      pull_request:
        enabled: true
        draft: false
        base:
          owner: hatamiarash7
          name: homebrew-tap
          branch: brews
